markdownExploder: true
qa:
  qaLocation: docs/qa
prd:
  prdFile: docs/Güncel/tasks.md
  prdVersion: v4
  prdSharded: false
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/Güncel/Architecture_better.md
  architectureVersion: v4
  architectureSharded: false
  architectureShardedLocation: docs/architecture
customTechnicalDocuments: null
devLoadAlwaysFiles:

devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
